services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
    container_name: Backend-studentFriends

  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend
    container_name: Frontend-studentFriends
